### ISSUE TITLE
Importing Numeric as Character

### ISSUE THREAD

**Issue by codydh** [DerekYves/rsurveygizmo#2]
First, thanks for the awesome project! This will be incredibly useful.

I'm not sure if it's intended or even solvable, but when I have purely numeric responses (e.g. radio buttons ranging 1–5), I still get these variables downloaded as characters instead of a numeric type. Is there something I can do about this, besides converting them manually?

**Comment by DerekYves** [comment]
Hi Cody,

As the SGizmo doesn't enforce a specific type of field I had to code it to
the lowest common denominator to make it work in all settings. What I have
generally done on my send is assign question aliases to all response items
that have a particular stub to indicate that it is a numeric response, thus
allowing something like:

data[ , grep("^nmb_question_", names(df))] <- sapply(data[ ,
grep("^nmb_question_", names(df))], as.numeric)

Best,
Derek

**Comment by bschneidr** [comment]
Keeping imports as character for the purposes of the `rsurveygizmo` functions is definitely the safest option, since it allows the user to reason consistently about what a given function returns.  
  
As a user, it's pretty easy to automatically convert responses to numeric whenever the conversion would be 'lossless'. For example, you might automatically convert `c("95","92")` to numeric but leave `c("95","92ish")` as character since the conversion in the former case would be 'lossless' while conversion in the second case would not be 'lossless'.  
  
For example, the following function converts a vector to numeric whenever the conversion is 'lossless':  
     
     convert_if_lossless <- function(x) {
            character_na <- is.na(x)
            character_empty <- !is.na(x) & x == ""

            x_numeric <- as.numeric(x)
            numeric_na <- is.na(x_numeric)
            
            loss <- numeric_na & !(character_na | character_empty)

            if (any(loss)) {
               x
            } else {
               x_numeric
            }
     }
